/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LettersIndexRouteImport } from './routes/letters.index'
import { Route as LettersSlugRouteImport } from './routes/letters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LettersRoute,
} as any)
const LettersSlugRoute = LettersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LettersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/letters': typeof LettersRouteWithChildren
  '/products': typeof ProductsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/letters/': typeof LettersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/letters': typeof LettersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/letters': typeof LettersRouteWithChildren
  '/products': typeof ProductsRoute
  '/letters/$slug': typeof LettersSlugRoute
  '/letters/': typeof LettersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contact' | '/letters' | '/products' | '/letters/$slug' | '/letters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/products' | '/letters/$slug' | '/letters'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/letters'
    | '/products'
    | '/letters/$slug'
    | '/letters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LettersRoute: typeof LettersRouteWithChildren
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/': {
      id: '/letters/'
      path: '/'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof LettersRoute
    }
    '/letters/$slug': {
      id: '/letters/$slug'
      path: '/$slug'
      fullPath: '/letters/$slug'
      preLoaderRoute: typeof LettersSlugRouteImport
      parentRoute: typeof LettersRoute
    }
  }
}

interface LettersRouteChildren {
  LettersSlugRoute: typeof LettersSlugRoute
  LettersIndexRoute: typeof LettersIndexRoute
}

const LettersRouteChildren: LettersRouteChildren = {
  LettersSlugRoute: LettersSlugRoute,
  LettersIndexRoute: LettersIndexRoute,
}

const LettersRouteWithChildren =
  LettersRoute._addFileChildren(LettersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LettersRoute: LettersRouteWithChildren,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
